- hosts: all
  gather_facts: False
  tasks:
    - name: Asegurar que tengo los repo actualizados
      apt:
        update_cache: true
        
    - name: Asegurar que tenga instalado curl
      apt:
        name: curl
        state: present
    
    - name: Comprobar que podamos hacer el curl
      shell: curl google.com
        
        